import pytest
import torq.performance
from filelock import FileLock


def pytest_addoption(parser):
    parser.addoption("--debug-ir", nargs='?', const=True, default=False, help="Enable detailed IR dump of after each pass (optionally set the dump directory)")
    parser.addoption("--generate-hw-test-vectors", action="store_true", default=False, help="Generate hardware test vectors")
    parser.addoption("--hw-test-vector-output-dir", default=False, help="Store hardware test vectors generated by test_torqrt.py in this directory")
    parser.addoption("--extra-torq-compiler-options", default=[], help="Add these extra options when compiling with the torq backend (use quotes to pass multiple arguments)")
    parser.addoption("--extra-torq-runtime-options", default=[], help="Add these extra options when executing a module with the torq runtime (use quotes to pass multiple arguments)")
    parser.addoption("--no-phases-dump", action="store_true", default=False, help="Disable phase dumps in torq compiler")
    parser.addoption("--debug-torq-compiler", type=int, default=0, help="Run torq compiler under gdb")
    parser.addoption("--trace-buffers", action="store_true", default=False, help="Enable tracing of buffers in the torq runtime")
    parser.addoption("--performance-report", action="store", default=False, help="Path to write test performance report CSV")
    parser.addoption("--recompute-cache", action="store_true", default=False, help="Re-creates all cached artifacts instead of using existing cached values")


def pytest_sessionstart(session):    

    # run this code only when runnning on the controller when using xdist
    # we don't want each worker to truncate the file
    if hasattr(session.config, "workerinput"):
        return

    performance_report = session.config.getoption("--performance-report")

    if performance_report:

        # Truncate the performance report file to ensure we clear out
        # any previous result that may be present. The test will append
        # to this file
        with open(performance_report, 'w') as fp:
            pass


@pytest.fixture
def scenario_log(request):    
    test_file = request.node.fspath.basename if hasattr(request.node, "fspath") else "unknown"
    scenario_log = torq.performance.ScenarioLog([test_file, request.node.name])

    yield scenario_log
    
    performance_report = request.config.getoption("--performance-report")
    
    if performance_report:

        # we need to take a lock because in xdist mode multiple workes
        # may try to write to the file at the same time
        with FileLock(performance_report + ".lock"):
            with open(performance_report, 'a') as fp:
                scenario_log.write(fp)
