description: Get AWS credentials from the container provider

outputs:
  access_key:
    description: 'AWS Access Key ID'
    value: ${{ steps.aws_creds.outputs.access_key }}

  secret_key:
    description: 'AWS Secret Access Key'
    value: ${{ steps.aws_creds.outputs.secret_key }}

  session_token:
    description: 'AWS Session Token'
    value: ${{ steps.aws_creds.outputs.session_token }}

runs:
  using: composite

  steps:
    - name: Get AWS credentials
      id: aws_creds
      shell: bash 
      run: |
        ${{ github.action_path }}/get_aws_creds.py
