"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z3-vwm@3-wtk4kp_odcx*4hiagl3x^kz15ru1clnv-&o=zme4f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

if os.environ.get("SPACE_HOST"):
    ALLOWED_HOSTS.append(os.environ.get("SPACE_HOST"))    

# Add extra allowed hosts from environment variable, comma separated
extra_hosts = os.environ.get("EXTRA_ALLOWED_HOSTS")
if extra_hosts:
    ALLOWED_HOSTS.extend([host.strip() for host in extra_hosts.split(",")])


# Add ECS container IP to allowed hosts if running in ECS
# (this is to let the load balancer health check work, which hits the container IP directly)
if os.environ.get("ECS_CONTAINER_METADATA_URI_V4"):
    print("Running in ECS, adding container IP to ALLOWED_HOSTS")

    import requests
    
    metadata_uri = os.environ.get("ECS_CONTAINER_METADATA_URI_V4")
    response = requests.get(metadata_uri, timeout=1)
    if response.status_code == 200:
        container_metadata = response.json()
        networks = container_metadata.get("Networks", [])
        for network in networks:
            if "IPv4Addresses" in network:
                for ip in network["IPv4Addresses"]:
                    ALLOWED_HOSTS.append(ip)
    else:
        print(f"Failed to retrieve container metadata, status code: {response.status_code}")

    

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'perf'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware'
]

ROOT_URLCONF = 'webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.get('PG_DATABASE_HOST'),
        'PORT': os.environ.get('PG_DATABASE_PORT'),
        'NAME': os.environ.get('PG_DATABASE_NAME'),
        'USER': os.environ.get('PG_DATABASE_USER'),
        'PASSWORD': os.environ.get('PG_DATABASE_PASSWORD'),
    }
}

# File storage

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": os.environ.get("S3_DATA_BUCKET"),
            "endpoint_url": os.environ.get("S3_ENDPOINT_URL"),
            "region_name": os.environ.get("AWS_REGION"),
        }
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'static'

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = '/data/media'

# Allow embedding the app from huggingface spaces
if os.environ.get("SPACE_HOST"):
    SECURE_CONTENT_SECURITY_POLICY = "frame-ancestors 'self' https://huggingface.co"

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"