FROM ubuntu:24.04

# Copy release package list from release
COPY apt-packages.txt /packages.txt

# Install dependencies
RUN apt-get update && \
    xargs -a /packages.txt apt-get install -y --no-install-recommends && \
    rm -rf /var/lib/apt/lists/* /packages.txt

# Create and activate a virtual environment for the wheel install
RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

# Copy requirements.txt from the dev tree
COPY requirements.txt /requirements.txt

# Install dependencies that were used to test the wheels
RUN pip3 install --no-cache-dir -r /requirements.txt

# Install x86_64 wheels
RUN --mount=type=bind,source=dist,target=/tmp/dist,ro \
    pip3 install --no-cache-dir /tmp/dist/*x86_64.whl
