FROM public.ecr.aws/ubuntu/ubuntu:24.04

RUN apt-get update && \
    apt-get install -y cmake lld wget curl git git-lfs sudo openssh-server vim \
        python3-pip python3-dev python3-venv python3-setuptools zip build-essential python3-venv python3-wheel && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --depth=1 https://github.com/aws/aws-fpga.git && \
    cd aws-fpga && \
    bash -c "source ./sdk_setup.sh" && \
    rm -rf aws-fpga

# this is taken from the "Create new action runner screen in GitHub organization settings" page
ARG GH_RUNNER_VERSION=2.331.0
ARG GH_RUNNER_HASH=5fcc01bd546ba5c3f1291c2803658ebd3cedb3836489eda3be357d41bfcf28a7

RUN mkdir /actions-runner && cd /actions-runner && \
    curl -o actions-runner-linux-x64-${GH_RUNNER_VERSION}.tar.gz -L https://github.com/actions/runner/releases/download/v${GH_RUNNER_VERSION}/actions-runner-linux-x64-${GH_RUNNER_VERSION}.tar.gz && \
    echo "${GH_RUNNER_HASH}  actions-runner-linux-x64-${GH_RUNNER_VERSION}.tar.gz" | shasum -a 256 -c && \
    tar xzf ./actions-runner-linux-x64-${GH_RUNNER_VERSION}.tar.gz && \
    rm actions-runner-linux-x64-${GH_RUNNER_VERSION}.tar.gz

COPY requirements.txt /code/requirements.txt

RUN python3 -m venv /workspace/venv

ENV PATH="/workspace/venv/bin:$PATH"

RUN /workspace/venv/bin/pip install -r /code/requirements.txt && \
    rm -rf /root/.cache

ENTRYPOINT ["bash", "-c", "/actions-runner/run.sh --jitconfig ${GH_JIT_CONFIG}" ]
