FROM public.ecr.aws/ubuntu/ubuntu:24.04

RUN apt-get update && \
    apt-get install -y cmake lld wget curl git git-lfs sudo openssh-server vim \
        python3-pip python3-dev python3-venv python3-setuptools zip build-essential python3-venv python3-wheel && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --depth=1 https://github.com/aws/aws-fpga.git && \
    cd aws-fpga && \
    bash -c "source ./sdk_setup.sh" && \
    rm -rf aws-fpga

RUN mkdir /actions-runner && cd /actions-runner && \
    wget https://github.com/actions/runner/releases/download/v2.329.0/actions-runner-linux-x64-2.329.0.tar.gz && \
    echo "194f1e1e4bd02f80b7e9633fc546084d8d4e19f3928a324d512ea53430102e1d  actions-runner-linux-x64-2.329.0.tar.gz" | shasum -a 256 -c - && \
    tar xvzf ./actions-runner-linux-x64-2.329.0.tar.gz && \
    rm actions-runner-linux-x64-2.329.0.tar.gz

COPY third_party/iree/runtime/bindings/python/iree/runtime/build_requirements.txt /code/build_requirements.txt
COPY third_party/iree/integrations/tensorflow/test/requirements.txt /code/tf_test_requirements.txt
COPY requirements.txt /code/requirements.txt

RUN python3 -m venv /workspace/venv

ENV PATH="/workspace/venv/bin:$PATH"

RUN /workspace/venv/bin/pip install -r /code/build_requirements.txt && \
    /workspace/venv/bin/pip install -r /code/tf_test_requirements.txt && \
    /workspace/venv/bin/pip install -r /code/requirements.txt && \
    rm -rf /root/.cache

ENTRYPOINT ["bash", "-c", "/actions-runner/run.sh --jitconfig ${GH_JIT_CONFIG}" ]