FROM public.ecr.aws/ubuntu/ubuntu:24.04

RUN apt-get update && \
    apt-get install -y cmake lld wget curl git git-lfs python3-pip python3-dev python3-venv python3-setuptools qemu-system-misc zip && \
    rm -rf /var/lib/apt/lists/*

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && ./aws/install && rm -rf awscliv2.zip && rm -rf /root/.cache

COPY third_party/iree/runtime/bindings/python/iree/runtime/build_requirements.txt /code/build_requirements.txt
COPY third_party/iree/integrations/tensorflow/test/requirements.txt /code/tf_test_requirements.txt
COPY requirements.txt /code/requirements.txt

RUN python3 -m venv /workspace/venv

ENV PATH="/workspace/venv/bin:$PATH"

RUN /workspace/venv/bin/pip install -r /code/build_requirements.txt && \
    /workspace/venv/bin/pip install -r /code/tf_test_requirements.txt && \
    /workspace/venv/bin/pip install -r /code/requirements.txt && \
    rm -rf /root/.cache
