#!/bin/bash

# get the base directory of the script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd $DIR/..

find compiler -name "*.h*" -or -name "*.c*" | xargs clang-format-18 -i
