# Generated by Django 6.0 on 2026-01-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.TextField()),
                ('name', models.TextField()),
                ('parameters', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profiling_data', models.FileField(upload_to='')),
                ('outcome', models.IntegerField(choices=[(1, 'Pass'), (2, 'Error'), (3, 'Expected Fail'), (4, 'Fail'), (5, 'Skip')])),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf.testcase')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf.testsession')),
            ],
        ),
    ]
