# Generated by Django 6.0 on 2026-01-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='profiling_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
