# Generated by Django 6.0 on 2026-01-07 15:09

import django.db.models.deletion
import perf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0002_alter_testrun_profiling_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='testsession',
            name='git_branch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='git_commit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='workflow_run_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='outcome',
            field=models.IntegerField(choices=[(1, 'Pass'), (2, 'Fail'), (3, 'Skip')]),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='profiling_data',
            field=models.FileField(blank=True, null=True, upload_to=perf.models.profiling_data_upload_path),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf.testrun')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf.metric')),
            ],
        ),
    ]
