# Generated by Django 6.0 on 2026-01-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0003_metric_testsession_git_branch_testsession_git_commit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='workflow_run_attempt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='testsession',
            constraint=models.UniqueConstraint(condition=models.Q(('git_commit__isnull', False), ('git_branch__isnull', False), ('workflow_run_id__isnull', False), ('workflow_run_attempt__isnull', False), _connector='OR'), fields=('git_commit', 'git_branch', 'workflow_run_id', 'workflow_run_attempt'), name='unique_git_workflow_when_all_non_null'),
        ),
    ]
