# Generated by Django 6.0 on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0004_testsession_owner_testsession_workflow_run_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='workflow_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveConstraint(
            model_name='testsession',
            name='unique_git_workflow_when_all_non_null',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='workflow_run_attempt',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='workflow_run_id',
        ),
        migrations.AddConstraint(
            model_name='testsession',
            constraint=models.UniqueConstraint(condition=models.Q(('workflow_url__isnull', False)), fields=('workflow_url',), name='unique_workflow_url'),
        ),
    ]
