# Generated by Django 6.0.4 on 2026-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0011_testrun_failure_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='testrunbatch',
            options={'verbose_name': 'Test run batch', 'verbose_name_plural': 'Test run batches'},
        ),
        migrations.AlterField(
            model_name='testrun',
            name='failure_log',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='outcome',
            field=models.IntegerField(choices=[(1, 'Pass'), (2, 'Fail'), (3, 'Skip'), (4, 'Error'), (5, 'XFail'), (6, 'NXPass')]),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('module', 'name', 'parameters'), name='unique_testcase_module_name_parameters'),
        ),
        migrations.AddField(
            model_name='testgroup',
            name='test_cases',
            field=models.ManyToManyField(to='perf.testcase'),
        ),
    ]
