# Generated by Django 6.0.4 on 2026-04-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0012_testgroup_alter_testrunbatch_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_metric_name'),
        ),
    ]
