# Generated by Django 6.0 on 2026-04-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0013_metric_unique_metric_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='linked_issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('test_run', 'metric'), name='unique_measurement_per_test_run_and_metric'),
        ),
        migrations.AddConstraint(
            model_name='testrun',
            constraint=models.UniqueConstraint(fields=('test_run_batch', 'test_case'), name='unique_test_run_per_batch_and_case'),
        ),
    ]
