# Generated by Django 6.0.4 on 2026-04-25 04:58

import django.db.models.deletion
from django.db import migrations, models


def populate_existing_testsession_fields(apps, schema_editor):
    TestSession = apps.get_model('perf', 'TestSession')
    TestSession.objects.update(test_plan='torq', completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0015_testsession_branch_timestamp_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compiler', models.TextField(blank=True, null=True)),
                ('compiler_input', models.TextField(blank=True, null=True)),
                ('compiler_target', models.TextField(blank=True, null=True)),
                ('compiler_options', models.TextField(blank=True, null=True)),
                ('runtime', models.TextField(blank=True, null=True)),
                ('runtime_target', models.TextField(blank=True, null=True)),
                ('runtime_hw_type', models.TextField(blank=True, null=True)),
                ('runtime_options', models.TextField(blank=True, null=True)),
                ('runtime_input', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='testsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsession',
            name='test_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_existing_testsession_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='test_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perf.testmetadata'),
        ),
    ]
