# Generated by Django 6.0.4 on 2026-04-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0016_testmetadata_testsession_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('hw_type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('inference_frequency', models.IntegerField(blank=True, null=True)),
                ('cache_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
