# Generated by Django 6.0.4 on 2026-04-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0017_runtimetarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimetarget',
            name='memory_bandwidth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runtimetarget',
            name='name',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='runtimetarget',
            constraint=models.UniqueConstraint(fields=('name', 'hw_type'), name='unique_runtime_target_name_hw_type'),
        ),
    ]
