# Generated by Django 6.0.4 on 2026-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0018_runtimetarget_memory_bandwidth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtimetarget',
            name='cache_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runtimetarget',
            name='inference_frequency',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runtimetarget',
            name='memory_bandwidth',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
