# Generated by Django 6.0.4 on 2026-06-19

from django.db import migrations, models


PREFERRED_METRIC_ORDER = [
    "total_duration",
    "total_npu_duration",
    "total_npu_operations",
    "compute_time",
    "slice_time",
    "dma_time",
    "css_time",
    "host_program",
    "host_program_time",
    "compilation_time",
    "model_size",
]


def populate_metric_priorities(apps, schema_editor):
    Metric = apps.get_model("perf", "Metric")
    for priority, metric_name in enumerate(PREFERRED_METRIC_ORDER):
        Metric.objects.filter(name=metric_name).update(priority=priority)


def reset_metric_priorities(apps, schema_editor):
    Metric = apps.get_model("perf", "Metric")
    Metric.objects.update(priority=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0019_alter_runtimetarget_cache_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="priority",
            field=models.PositiveIntegerField(db_index=True, default=1000),
        ),
        migrations.RunPython(populate_metric_priorities, reset_metric_priorities),
    ]
