// Copyright 2024 SYNAPTICS Inc.
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#pragma once

#include "Passes.h"

#include "torq/Dialect/TorqHL/TorqHLDialect.h"
#include "torq/Dialect/TorqHW/TorqHWDialect.h"

#include "iree/compiler/Dialect/HAL/IR/HALDialect.h"

#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"

#include "mlir/Interfaces/FunctionInterfaces.h"
#include "mlir/Pass/Pass.h"

namespace mlir::syna::torq {

#define GEN_PASS_DECL

#define GEN_PASS_DEF_ADDDEALLOCATION
#define GEN_PASS_DEF_ANALYZETENSORSIZES
#define GEN_PASS_DEF_ASSIGNDTCMITCMXRAMADDRESSES
#define GEN_PASS_DEF_ASSIGNLRAMADDRESSES
#define GEN_PASS_DEF_ASSIGNNSSPROGRAMSADDRESSES
#define GEN_PASS_DEF_ASSIGNOBJECTSIDENTIFIERS
#define GEN_PASS_DEF_ASSIGNOPERATIONSTOCPUPROGRAMS
#define GEN_PASS_DEF_CHECKCSSSTACKSIZE
#define GEN_PASS_DEF_COMPILECPUPROGRAMS
#define GEN_PASS_DEF_COMPILENSSINVOCATIONS
#define GEN_PASS_DEF_COMPILESLICEINVOCATIONS
#define GEN_PASS_DEF_CONVERTTENSORPADTOLINALG
#define GEN_PASS_DEF_COMPILETIMECONSTCOMPUTE
#define GEN_PASS_DEF_COMPILETIMECONSTOUTLINE
#define GEN_PASS_DEF_CREATEGLOBALS
#define GEN_PASS_DEF_DTCMTILE
#define GEN_PASS_DEF_EXECUTORASSIGNMENT
#define GEN_PASS_DEF_ENCODETENSORS
#define GEN_PASS_DEF_FOLDCONVERT
#define GEN_PASS_DEF_FUSEACTWITHCONV
#define GEN_PASS_DEF_KERNELSELECTION
#define GEN_PASS_DEF_LINALGSLICING
#define GEN_PASS_DEF_LOWERARITHCONSTANTS
#define GEN_PASS_DEF_LOWERCALLPROGRAMTOSTARTWAIT
#define GEN_PASS_DEF_LOWERHOSTCOPIESTONPU
#define GEN_PASS_DEF_LRAMTILE
#define GEN_PASS_DEF_MAPBINDINGS
#define GEN_PASS_DEF_MARKHOSTEXECUTOR
#define GEN_PASS_DEF_OUTLINECPUPROGRAMS
#define GEN_PASS_DEF_OUTLINENSSPROGRAMS
#define GEN_PASS_DEF_OUTLINESLICETASKS
#define GEN_PASS_DEF_PEELTILELOOPS
#define GEN_PASS_DEF_PROFILING
#define GEN_PASS_DEF_REPLACEFORLOOPSWITHFIRSTITERATION
#define GEN_PASS_DEF_RESOLVEADDRESSES
#define GEN_PASS_DEF_RESOLVEINVOCATIONARGUMENTS
#define GEN_PASS_DEF_SCALARSTOTENSORS
#define GEN_PASS_DEF_SEGMENTNSSPROGRAMS
#define GEN_PASS_DEF_SLICING
#define GEN_PASS_DEF_STRIPTORQEXECUTORATTR
#define GEN_PASS_DEF_TORQLOWEREXECUTABLETARGET
#define GEN_PASS_DEF_TILEANDFUSE
#define GEN_PASS_DEF_TORQHLTILE
#define GEN_PASS_DEF_UNROLLDYNAMICSHAPELOOP
#define GEN_PASS_DEF_UNROLLLOOP
#define GEN_PASS_DEF_VALIDTOSAMEPADPASS

#include "torq/Codegen/Passes.h.inc"

} // namespace mlir::syna::torq
