name: Build mpact

on:
  workflow_call:    
    outputs:
      cache_key:
        description: Cache key of the built artifact
        value: ${{ jobs.build.outputs.cache-key }}

      path:
        description: Path to the built artifact
        value: ${{ jobs.build.outputs.path }}

env:
  MPACT_REF: 2e1097cb199ec6511c4990cbf3cead46443b3fc4

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      cache-key: ${{ steps.gen_vars.outputs.cache_key }}
      path: ${{ steps.gen_vars.outputs.path }}

    steps:

      - name: Checkout actions
        uses: actions/checkout@v6

      - name: Generate cache key and paths
        id: gen_vars
        run: |
          echo "cache_key=mpact-${{ env.MPACT_REF }}-${{ hashFiles('.github/workflows/build-mpact.yml') }}" >> $GITHUB_OUTPUT
          echo "path=coralnpu-mpact-simulator-${{ env.MPACT_REF }}.tar.gz" >> $GITHUB_OUTPUT

      - id: lookup_cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ steps.gen_vars.outputs.path }}
          key: ${{ steps.gen_vars.outputs.cache_key }}
          lookup-only: true

      - name: Checkout coralnpu-mpact
        uses: actions/checkout@v6
        if: steps.lookup_cache.outputs.cache-hit != true
        with:
          repository: synaptics-torq/coralnpu-mpact
          ref: ${{ env.MPACT_REF }}
          path: coralnpu-mpact
      
      - name: Build mpact simulation library
        if: steps.lookup_cache.outputs.cache-hit != 'true'
        run: |
          cd coralnpu-mpact
          bazel build sim/hw_sim:libcoralnpu_simulator_mpact.so

      - name: Package the mpact simulation library
        if: steps.lookup_cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p mpact-lib
          cp coralnpu-mpact/bazel-bin/sim/hw_sim/libcoralnpu_simulator_mpact.so mpact-lib/
          cp coralnpu-mpact/sim/hw_sim/coralnpu_simulator.h mpact-lib/
          tar -czvf ${{ steps.gen_vars.outputs.path }} -C mpact-lib .

      - name: Upload to cache
        if: steps.lookup_cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: ${{  steps.gen_vars.outputs.path }}
          key: ${{ steps.gen_vars.outputs.cache_key }}
      