name: Build FPGA tests image

on:
  workflow_call:
    outputs:
      image_name:
        description: Name of the built Docker image
        value: ${{ jobs.build.outputs.image_name }}

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-docker-ecr.yml
    with:
      docker_file: scripts/Dockerfile.ci-fpga-tests
      sources: >-
        scripts/install_dependencies.sh
        scripts/configure_python.sh
        requirements.txt
      extra_tags: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'latest-fpga-tests' || '' }}
          
