name: Build Kernel module dependencies

on:
  workflow_call:    
    outputs:
      cache_key:
        description: Cache key of the built artifact
        value: ${{ jobs.build.outputs.cache-key }}

      path:
        description: Path to the built artifact
        value: ${{ jobs.build.outputs.path }}


jobs:

  build:    
    name: Build
    runs-on: ubuntu-latest

    outputs:
      cache-key: ${{ steps.gen_vars.outputs.cache_key }}
      path: ${{ steps.gen_vars.outputs.path }}

    steps:

    - name: Checkout actions and scripts
      uses: actions/checkout@v6
      
    - name: Generate cache key and paths
      id: gen_vars
      run: |
        echo "cache_key=ko-deps-${{ hashFiles('.github/workflows/build-ko-dependencies.yml', 'scripts/setup_soc_ko_build_deps.sh') }}" >> $GITHUB_OUTPUT
        echo "path=third_party/runtimes-prebuilt/soc-kernel/syna-kernel-artifacts.tgz" >> $GITHUB_OUTPUT

    - id: lookup_cache
      uses: actions/cache/restore@v5
      with:
        path: ${{ steps.gen_vars.outputs.path }}
        key: ${{ steps.gen_vars.outputs.cache_key }}
        lookup-only: true
    
    - name: Install dependencies
      if: steps.lookup_cache.outputs.cache-hit != 'true'
      run: |

        # install the dependencies instead of using the CI docker to avoid circular dependencies between 
        # the docker image and the kernel module artifacts
        sudo apt-get update
        sudo apt-get install -y binutils-arm-linux-gnueabihf gcc-aarch64-linux-gnu flex bison bc

    - name: Build Kernel Module dependenencies
      if: steps.lookup_cache.outputs.cache-hit != 'true'
      run: |
        scripts/setup_soc_ko_build_deps.sh    

    - name: Upload to cache
      if: steps.lookup_cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ${{  steps.gen_vars.outputs.path }}
        key: ${{ steps.gen_vars.outputs.cache_key }}
