name: Build TensorFlow binaries

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-tensorflow.yml'
  
  pull_request:    
    paths:
      - '.github/workflows/build-tensorflow.yml'

  release:
    types: [published]


concurrency:
  group: build-tensorflow-${{ github.ref }}
  cancel-in-progress: true


env:
  TF_VERSION: v2.20.0

jobs:

  build:

    runs-on:
    - codebuild-${{ vars.CODEBUILD_PROJECT_CODEBASE }}-${{ github.run_id }}-${{ github.run_attempt }}
      image:ubuntu-7.0
      instance-size:xlarge 

    permissions:
      contents: write
      actions: write

    steps:

    - name: Update checkout
      uses: actions/checkout@v6      

    - name: Checkout tensorflow
      uses: actions/checkout@v6
      with:
        repository: tensorflow/tensorflow
        ref: ${{ env.TF_VERSION }}
        path: tensorflow

    - name: Install bazelisk
      run: |        
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.27.0/bazelisk-linux-amd64"
        chmod +x bazelisk-linux-amd64
        mv bazelisk-linux-amd64 /usr/local/bin/bazel

    - name: Install clang
      run: |
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.2/clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz

        tar -xf clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz
        
        cp -r clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04/* /usr
    
    - name: Configure build
      run: |
        cd tensorflow
        yes "" | ./configure
    
    - name: Build TensorFlow binaries
      run: |
        cd tensorflow
        bazel build //tensorflow/compiler/mlir/lite:flatbuffer_translate //tensorflow/compiler/mlir/tosa:tf-tosa-opt

    - name: Create zip package
      run: |        
        mkdir tflite-tools-${{ env.TF_VERSION }}

        cp tensorflow/bazel-bin/tensorflow/compiler/mlir/lite/stablehlo/libcomposite_utils.so \
            tensorflow/bazel-bin/tensorflow/core/ir/libDialect.so \
            tensorflow/bazel-bin/external/llvm-project/llvm/libSupport.so \
            tensorflow/bazel-bin/external/llvm-project/mlir/libDestinationStyleOpInterface.so \
            tensorflow/bazel-bin/external/llvm-project/mlir/libPDLDialect.so \
            tensorflow/bazel-bin/external/llvm-project/mlir/libSparseTensorDialect.so \
            tensorflow/bazel-bin/tensorflow/compiler/mlir/lite/flatbuffer_translate \
            tensorflow/bazel-bin/tensorflow/compiler/mlir/tosa/tf-tosa-opt.runfiles/org_tensorflow/tensorflow/compiler/mlir/tosa/tf-tosa-opt \
            tflite-tools-${{ env.TF_VERSION }}/

        zip -r tflite-tools-${{ env.TF_VERSION }}.zip tflite-tools-${{ env.TF_VERSION }}

    - name: Ensure snapshot release exists
      uses: ./.github/actions/ensure-snapshot-release
      if: ${{ github.event_name == 'push' }}
      with:
        github_token: ${{ secrets.github_token }}

    - name: Upload to GitHub release
      uses: ./.github/actions/upload-to-release
      with:
        github_token: ${{ secrets.github_token }}
        assets_glob: tflite-tools-${{ env.TF_VERSION }}.zip

    - name: Rebuild Docker images to include new TensorFlow binaries
      if: ${{ github.event_name == 'push' }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh workflow run build-docker.yml --ref ${{ github.ref }}
        gh workflow run build-docker-ecr.yml --ref ${{ github.ref }}
        