name: Build Kernel module dependencies

on:
  workflow_call:
    secrets:
      LINUX_KERNEL_SSH_KEY:
        required: true
    outputs:
      cache_key:
        description: Cache key of the built artifact
        value: ${{ jobs.build.outputs.cache-key }}

      path:
        description: Path to the built artifact
        value: ${{ jobs.build.outputs.path }}


jobs:

  build:
    name: Build

    # we build on AWS to ensure we can access internal resources, we use a default image to avoid dependencies
    runs-on:
      - codebuild-${{ vars.CODEBUILD_PROJECT_CODEBASE }}-${{ github.run_id }}-${{ github.run_attempt }}
        image:ubuntu-7.0

    outputs:
      cache-key: ${{ steps.gen_vars.outputs.cache_key }}
      path: ${{ steps.gen_vars.outputs.path }}

    steps:

    - name: Checkout actions and scripts
      uses: actions/checkout@v6

    - name: Generate cache key and paths
      id: gen_vars
      run: |
        echo "cache_key=ko-deps-${{ hashFiles('.github/workflows/build-ko-dependencies.yml', 'scripts/setup_soc_ko_build_deps.sh') }}" >> $GITHUB_OUTPUT
        echo "path=third_party/runtimes-prebuilt/soc-kernel/syna-kernel-artifacts.tgz" >> $GITHUB_OUTPUT

    - name: Install zstd
      run: |
        # zstd is used to compress the cache artifact by the action/cache plugin, and is not installed by default on ubuntu 22.04
        # It must be installed before the cache lookup because actions/cache hashes the compression method into the cache version.
        sudo apt-get update
        sudo apt-get install -y zstd

    - id: lookup_cache
      uses: actions/cache/restore@v5
      with:
        path: ${{ steps.gen_vars.outputs.path }}
        key: ${{ steps.gen_vars.outputs.cache_key }}
        lookup-only: true

    - name: Install dependencies
      if: steps.lookup_cache.outputs.cache-hit != 'true'
      run: |

        # install the dependencies instead of using the CI docker to avoid circular dependencies between
        # the docker image and the kernel module artifacts
        sudo apt-get install -y binutils-arm-linux-gnueabihf gcc-aarch64-linux-gnu flex bison bc

    - name: Build Kernel Module dependenencies
      if: steps.lookup_cache.outputs.cache-hit != 'true'
      env:
        LINUX_REPO_URL: ${{ vars.LINUX_REPO_URL }}
        LINUX_DRIVER_REPO_URL: ${{ vars.LINUX_DRIVER_REPO_URL }}
        LINUX_KERNEL_SSH_KEY: ${{ secrets.LINUX_KERNEL_SSH_KEY }}
        LINUX_KERNEL_SSH_OPTIONS: ${{ vars.LINUX_KERNEL_SSH_OPTIONS }}
        LINUX_KERNEL_SSH_HOST_KEY: ${{ vars.LINUX_KERNEL_SSH_HOST_KEY }}
      run: |
        scripts/setup_soc_ko_build_deps.sh

    - name: Upload to cache
      if: steps.lookup_cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ${{  steps.gen_vars.outputs.path }}
        key: ${{ steps.gen_vars.outputs.cache_key }}
