name: Build and deploy documentation website

on: 
  workflow_dispatch:
  pull_request:    
    paths:
      - 'doc/**'
      - '.github/workflows/doc.yml'
  push:
    branches:
       - main
    paths:
      - 'doc/**'
      - '.github/workflows/doc.yml'

  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true  

jobs:
  site_build:
      name: Build documentation site

      permissions:
          actions: write
          contents: write
          pages: write
          id-token: write

      uses: syna-astra-dev/action-doc-publish/.github/workflows/process.yml@v3
      with:
        checkout_submodules: false
        doc_directory: doc
        update_site: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}