name: Evaluate External Compilation Engines

on: 

  # workflow_dispatch is used on main and vX.Y branches to generate official data
  workflow_dispatch:

  # pull_request is used to test changes to the external engine support
  pull_request:
    

concurrency:  
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true  

jobs:

  choose_runner_image:
    name: Choose runner image
    uses: ./.github/workflows/choose-runner.yml
    if: contains(github.event.pull_request.labels.*.name, 'test-alt-engines') || github.event_name == 'workflow_dispatch'

  test:    
    name: Test with external engines

    timeout-minutes: 50

    needs: [choose_runner_image]

    runs-on:
          - codebuild-${{ vars.CODEBUILD_PROJECT_CODEBASE }}-${{ github.run_id }}-${{ github.run_attempt }}
            image:custom-linux-${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ needs.choose_runner_image.outputs.image_name }}-tests

    permissions:
      contents: read
      id-token: write

    steps:
      
      # this is required to be able to download artifacts from S3
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v6
        id: assume_role
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ github.ref == 'refs/heads/main' && vars.MAIN_BRANCH_ROLE_ARN  || vars.PULL_REQUEST_ROLE_ARN }}

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: false
          submodules: false
    
      - name: Run tests with alternative engines
        uses: ./.github/actions/tests
        with:
          app_id: ${{ vars.CI_APP_ID }}
          app_private_key: ${{ secrets.CI_APP_PRIVATE_KEY }}
          extra_repo: ${{ vars.EXTRAS_REPO }}
          release_run_id: none # we run the tests without a release package
          setup_external_engine_requirements: true
          hf_token: ${{ secrets.HF_TOKEN }}
          pytest_args: -m alternative_engines -n auto --tflite-layer-test-generate-full-model-only --test-plan alt
          torq_perf_server: ${{ contains(github.event.pull_request.labels.*.name || '', 'test-stage-dashboard') && vars.DASHBOARD_URL_TORQ_COMPILER_DEV_DASHBOARD_STAGE || vars.DASHBOARD_URL_TORQ_COMPILER_DEV_DASHBOARD_PROD }}
          batch_name: alternative-engines
          s3_hf_cache_bucket: ${{ vars.SCCACHE_BUCKET }}
          s3_hf_cache_dir: hf_cache

  mark_complete:
    name: Mark workflow complete
    if: needs.test.result != 'skipped' && always()
    needs: [test]
    uses: ./.github/workflows/mark-workflow-complete.yml

