name: Evaluate External Compilation Engines

on:
  workflow_dispatch:

concurrency:  
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true  

permissions:
    contents: read
    id-token: write # required to assume the role in AWS

jobs:

  docker_image_tests:
    name: Build test image
    uses: ./.github/workflows/build-docker-image-tests.yml
  
  test:    
    name: Test with external engines

    timeout-minutes: 50

    needs: [docker_image_tests]

    runs-on:
      - codebuild-${{ vars.CODEBUILD_PROJECT_CODEBASE }}-${{ github.run_id }}-${{ github.run_attempt }}
        image:custom-linux-${{ needs.docker_image_tests.outputs.image_name }}

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: false
          submodules: false

      # this is required to be able to download artifacts from S3
      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        id: configure-aws-credentials
        with:
          aws_region: ${{ vars.AWS_REGION }}
          protected_role_arn: ${{ vars.MAIN_BRANCH_ROLE_ARN }}
          non_protected_role_arn: ${{ vars.PULL_REQUEST_ROLE_ARN }}
    
      - name: Run tests with alternative engines
        uses: ./.github/actions/tests
        with:
          app_id: ${{ vars.CI_APP_ID }}
          app_private_key: ${{ secrets.CI_APP_PRIVATE_KEY }}
          extra_repo: ${{ vars.EXTRAS_REPO }}
          release_run_id: none # we run the tests without a release package
          setup_external_engine_requirements: true
          hf_token: ${{ secrets.HF_TOKEN }}
          pytest_args: -m alternative_engines -n auto --tflite-layer-test-generate-full-model-only --test-plan alt
          torq_perf_server: ${{ contains(github.event.pull_request.labels.*.name || '', 'test-stage-dashboard') && vars.DASHBOARD_URL_TORQ_COMPILER_DEV_DASHBOARD_STAGE || vars.DASHBOARD_URL_TORQ_COMPILER_DEV_DASHBOARD_PROD }}
          batch_name: alternative-engines
          s3_hf_cache_bucket: ${{ vars.SCCACHE_BUCKET }}
          s3_hf_cache_dir: hf_cache

  mark_complete:
    name: Mark workflow complete
    if: needs.test.result != 'skipped' && always()
    needs: [test]
    uses: ./.github/workflows/mark-workflow-complete.yml

